# Generated by Django 3.2.7 on 2021-09-20 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('app_pass', models.CharField(max_length=100)),
                ('other_detail', models.CharField(max_length=500)),
                ('updated_on', models.DateField(verbose_name=datetime.date(2021, 9, 20))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
