# Generated by Django 3.2.7 on 2021-09-21 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordstore',
            name='app_or_web',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordstore',
            name='updated_on',
            field=models.DateField(verbose_name=datetime.date(2021, 9, 21)),
        ),
    ]
