# Generated by Django 3.2.7 on 2021-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20210921_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstore',
            name='app_or_web',
            field=models.CharField(max_length=100),
        ),
    ]
