# Generated by Django 3.2.7 on 2021-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_passwordstore_app_or_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstore',
            name='app_or_web',
            field=models.CharField(max_length=120),
        ),
    ]
